import { FileInput } from "@/components/file-input";
import SearchInput from "@/components/search-input";
import Folder from "@/components/folder";
import Navbar from "@/components/layout/navbar";
import Aside from "@/components/layout/aside";
import { Fragment } from "react";
import Link from "next/link";
import FileTable from "@/components/file-table";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Fileno-File Management Platform",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Fragment>
      <Navbar />
      <main className="container h-[92vh] grid grid-cols-1 lg:grid-cols-12 gap-10 mx-auto py-10">
        <article className="w-full md:col-span-8 lg:col-span-9 space-y-10">
          <section className="flex flex-col lg:flex-row justify-between gap-3">
            <h2 className="text-4xl">Welcome Back, Hinata</h2>
            <SearchInput />
          </section>

          <section className="flex flex-col gap-6">
            <h3 className="font-semibold">Recent files</h3>
            <div className="grid  grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-3">
              <Folder />
              <Folder />
              <Folder />
            </div>
          </section>

          <section className="flex flex-col gap-6">
            <h3 className="font-semibold">Upload files</h3>
            <FileInput />
          </section>

          <section className="flex flex-col gap-6">
            <div className="flex items-center justify-between ">
              <h3 className="font-semibold">Your files</h3>
              <Link href="/files" className="underline text-sm">
                View All
              </Link>
            </div>
            <FileTable />
          </section>
        </article>

        <Aside />
      </main>
    </Fragment>
  );
}
